# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check FreePlay Website

on:
  schedule:
    - cron: "0 * * * 2"   # Every hour on Tuesdays
    - cron: "0 */6 * * *" # Every 6 hours on other days
  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Print Working Directory
        run: pwd
        
      - name: List Files and Permissions
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python FreePlay_Releases.py
        

